// apps/saman/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'nxdemo-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'saman';
}

<div style="text-align:center">
  <nxdemo-greeting [title]="title"></nxdemo-greeting>
    <nxdemo-nxdemolib [title]="title"></nxdemo-nxdemolib>
</div>
<div style="margin-top: 150px; text-align:center">
  <img alt="Nx_Image" width="300" src="/assets/nx-logo.png" />
  <h2>This is an Angular app built with <a href="https://nx.dev">Nx</a>.</h2>
  <h2>🔎 **Nx is a set of Angular CLI power-ups for modern development.**</h2>
  <div>

// apps/reactapp/src/app/app.tsx
import * as React from 'react';
import { Component } from 'react';

import './app.css';

export class App extends Component {
  render() {
    const title = 'reactappTest';
    return (
      <div>
        <div style={{ textAlign: 'center' }}>
          <nxdemo-greeting title={title} />
        </div>
        <div style={{ marginTop: '150px', textAlign:'center' }}>
        <img alt="Nx_Image" width="300" src="assets/nx-logo.png" />
        <h2>This is an React app built with <a href="https://nx.dev">Nx</a>.</h2>
        <h2>🔎 **Nx is a set of Angular CLI power-ups for modern development.**</h2>
      </div>
      </div >
    );
  }
}
